### ISSUE TITLE
How to commit the current branch 

### ISSUE THREAD

**Issue by hantsy** [EndBug/add-and-commit#155]
I have set a scheduled workflow to syncing the medium post to my personal homepage. Due to the limitation of schedule, it only works on master branch.

https://github.com/hantsy/hantsy.github.io/blob/master/.github/workflows/medium-sync.yml

The checkout actions use a `ref: source` to switch to the `source` branch.

But I used this action(EndBug/add-and-commit) to commit changes and set `branch` to `source`, **but it is no effect, it commits to master.**

You can see the newly generated files in the `_posts` folder in the master branch.

https://github.com/hantsy/hantsy.github.io/tree/master/_posts

I want to push the generated files to the `source` branch.

**Comment by EndBug** [comment]
Hi, I've taken a look at your repo and I've seen that you've added the `branch` input only in this commit: https://github.com/hantsy/hantsy.github.io/commit/7b4921eef40eb9778a92eebeed741af7a748f375

The problem is that as of now there hasn't been any workflow run of the rss workflow: currently, the last rss run is [this](https://github.com/hantsy/hantsy.github.io/actions/runs/703389590), which runs on a version of the workflow that doesn't have the `branch` input. 
The only run that I see on that commit is [this](https://github.com/hantsy/hantsy.github.io/runs/2237489029), from the [deploy workflow](https://github.com/hantsy/hantsy.github.io/actions/runs/705191453/workflow): this is the workflow that pushed to master, and it doesn't contain `add-and-commit`.

If I've interpreted things correctly, you'll just need to either wait for the schedule to trigger a run from the rss workflow, or manually trigger one.

If you still have issues after running the actual workflow with the action, feel free to write here ;)

**Comment by hantsy** [comment]
@EndBug  Yesterday I was trying to perform a manual execution of rss workflow.

But today when I checked the source branch, the new blog entry is generated by scheduling settings.  

https://github.com/hantsy/hantsy.github.io/blob/source/_posts/2021-03-31-generate-a-jakarta-ee-9-project-skeleton-from-maven-archetype.html

But the commit from the github-actions bot did not trigger the deploy workflow, I need any othe settings on `deploy` workflow.

**Comment by EndBug** [comment]
Using the default token will prevent your commits from triggering further action runs. To avoid this kind of behavior, you'll have to use a custom PAT.
Anyway, that's something you'll have to in `actions/checkout`, my action only uses the token that the repo has been configured with.
