### ISSUE TITLE
[Question] How can I commit to other repo the same user?

### ISSUE THREAD

**Issue by DmitrijOkeanij** [EndBug/add-and-commit#17]
I am trying to commit to my other repo, but do not understand how.
I got this error
![image](https://user-images.githubusercontent.com/10674646/73137476-88dab600-4069-11ea-8fdf-abd1f60aa695.png)
And this script
![image](https://user-images.githubusercontent.com/10674646/73137491-b1fb4680-4069-11ea-86b3-40edc7e4b08a.png)

**Comment by EndBug** [comment]
I think this comes from the fact that you're using the `force` option with a `*.*` matcher, and that makes git try to commit those files too (which it shouldn't since they're supposed to be local).
I guess you could just try using `*.txt*` as the `pattern`.

**Comment by DmitrijOkeanij** [comment]
Now get this
![image](https://user-images.githubusercontent.com/10674646/73140013-21cafa80-4085-11ea-8db8-1505f00b9a74.png)
And the second question how to upload all files.
* as pattern is not working too.

**Comment by EndBug** [comment]
That is because the token you're using doesn't give the permissions to push to the second repository: the default [`GITHUB_TOKEN`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token) secret is meant to be used only with the repo the workflow is running in.
I think you need to create a custom GitHub token: you can find out how to do it [here](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token).

To add all the files you can either:

- Use `*.*` as the pattern but without the `force` option
- Use a pattern that excludes the `.git` folder: it may be something like `./!(.git)/*.*`, but I'm not sure about that

Anyway, try searching that on Google/StackOverflow/..., I'm sure you'll find something that works for you: the action uses a standard `find` command, [these](https://github.com/EndBug/add-and-commit/blob/925751a40629ea6bf28992ef065c5a0f3b1f6ad9/src/entrypoint.sh#L26) are the lines with the commands if you need them.

**Comment by DmitrijOkeanij** [comment]
I am not sure that this is possible to exclude something if linux find commend using pattern.
All answers like [this](https://stackoverflow.com/questions/4210042/how-to-exclude-a-directory-in-find-command) and propose to use  -not -path arguments witch is not possible using here.
```
find -name "*.js" -not -path "./directory/*"
```
May be to add code of ignoring .git folder to this repo, or to make some arguments to allow exclusions to find?

**Comment by EndBug** [comment]
I've created a new issue just for that, I will add it soon. For now, I'll close this one.

**Comment by EndBug** [comment]
@all-contributors please add @DmitrijOkeanij for ideas
