### ISSUE TITLE
I'm getting "error: failed to push some refs to repo"

### ISSUE THREAD

**Issue by aloj22** [EndBug/add-and-commit#217]
I want to add some files wheneever I push to a branch, I worked fine the first time but after that I'm getting this error. I've tried adding differents pull_strategy but none of them work. This is my action script

`name: Generate files

on:
  push:
    branches:
       feature/test_branch

jobs:

  generate_files:

    name: Generate files

    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2.1.1

        - name: Set up JDK 1.8
          uses: actions/setup-java@v1.4.3
          with:
            java-version: 1.8

        - name: Generate files
          run: ./gradlew -b generate_files.gradle

        - name: Commit files
          uses: EndBug/add-and-commit@v7
          with:
            default_author: github_actions
            add: .github/workflows`
            
          
`Error: Error: Pushing to https://github.com/Yuvod/yuvod-app-android-tv
POST git-receive-pack (1446 bytes)
error: failed to push some refs to 'https://github.com/Yuvod/yuvod-app-android-tv'`

**Comment by EndBug** [comment]
Please post a permalink to the failing action run or, if the repo is private, the complete log of the step that uses `add-and-commit`

**Comment by aloj22** [comment]
It was due to missing workflow permission in token. It was fixed by using a PAT with this permission. It can be closed.

**Comment by loomchild** [comment]
Hi,

I am facing the same issue I believe: https://github.com/loomchild/webflow-git-sites/runs/3530813268

It started happening after modifying the repo manually (not via workflow). I will run some more tests later to reproduce / isolate the issue.

Could you share what were the missing permissions? I would prefer to stick to standard token and avoid using PAT if possible, since I'd like to keep the configuration process simple for other users.

**Comment by loomchild** [comment]
The log is (maybe different than original reporter):
```
Error: Error: Pushing to https://github.com/loomchild/webflow-git-sites
POST git-receive-pack (57 bytes)
error: failed to push some refs to 'https://github.com/loomchild/webflow-git-sites'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by loomchild** [comment]
I don't understand how there could be any work in remote that is not present locally, if I checked out the repo just 2 steps before. Maybe some missing option in checkout action (depth?), or some sort of cache..

Anyway I was wondering of you came across such issue (I am fairly new to GH Actions). Thanks in advance for any help.

**Comment by EndBug** [comment]
@loomchild I think it's better if we discuss this in a new issue, since every case is different, even if the error is the same ;)

**Comment by loomchild** [comment]
@EndBug You are totally right.

I tried to reproduce the error, but without luck. I think that there might be something wrong with the repo, since even merging changes from upstream didn't work at some point.

I will raise a new bug once it happens again, so I can provide more information.

Thanks for your help!
