### ISSUE TITLE
could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by jpatel-fpmx** [EndBug/add-and-commit#222]
**Describe the bug**
Getting below error when I am using PAT TOKEN in Workflow of Github Actions while taking GIT checkout, commit and push in the protected branch. 

could not read Username for 'https://github.com': No such device or address

**Workflow used**
 steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        token: ${{ secrets.GH_TOKEN }}
    - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        push: true
        default_author: github_actor
        branch: main
        message: 'Sample commit messages'

**Expected behavior**
Should be able to push changes in protected branch

**Logs**
could not read Username for 'https://github.com': No such device or address

**Comment by EndBug** [comment]
As stated in the action manifest, you're not supposed to use the `github_token` input since it's not used to create and push commits. If you want to use your PAT, you just need to set it in `actions/checkout`: you need to remove the `persist_credentials: false`, since that prevents my action from knowing how to authenticate.

To sum it up, remove `persist_credentials` from `actions/checkout` and `github_token` from `add-and-commit`

**Comment by jpatel-fpmx** [comment]
Thanks Federico for your suggestion. My issue has been resolved now.
