### ISSUE TITLE
Question about pull strategy

### ISSUE THREAD

**Issue by smutel** [EndBug/add-and-commit#246]
Hello,

My github actions is failing due to wrong pull strategy I suppose.
https://github.com/smutel/go-netbox/runs/3175188541?check_suite_focus=true

In which case `--rebase` could work ?
Or could you please explain the behavior of each pull strategy even if it more related to git itself than your github actions ?

Thanks.

**Comment by EndBug** [comment]
Sorry about not replying earlier, I forgot to mark the notification as "unread" and then forgot about the issue 😅 

Honestly, I'm not really familiar with pull strategies, I only added the option because in some cases people needed to change it. From the [`git pull` docs](https://git-scm.com/docs/git-pull#_description) it says that `--rebase` uses `git rebase` instead of `git merge`, but I don't know how that affects your workflow in your specific case.
Anyway, I've seen that using the default option works for you ([link](https://github.com/smutel/go-netbox/runs/3175350292?check_suite_focus=true#step:7:1)), so I guess the issue is solved (?)

**Comment by smutel** [comment]
Yes, thanks.
