### ISSUE TITLE
Your local changes to the following files would be overwritten by checkout

### ISSUE THREAD

**Issue by cadop** [EndBug/add-and-commit#247]
I am getting the same error as https://github.com/EndBug/add-and-commit/issues/187 even when using the suggested `        pull_strategy: NO-PULL `

I have an empty folder on a separate branch, B (not the one the action runs on, A)
I commit to A, then the workflow runs fine and updates B. 
I commit again to A, then the workflow gives the error
```
Error: Error: error: Your local changes to the following files would be overwritten by checkout:
  	docs/build/doctrees/environment.pickle
  	docs/build/html/api_basic-1.pdf
....
```

Under 'Commit changes'
https://github.com/cadop/seg1d/runs/3205950974?check_suite_focus=true 

The (most) relevant part of workflow is:
```
    - name: Build documentation with sphinx
      run: |
        cd docs
        make clean
        make html
        make latexpdf
        ls
        cd ..
    - name: Commit changes
      uses: EndBug/add-and-commit@v7.2.0
      with:
        branch: documentation
        default_author: github_actions
        message: 'Auto-built sphinx documentation'
        add: 'docs'
        pull_strategy: NO-PULL 
```

I assume its something about docs, or commits, but I am so confused on using the workflow. I tried for awhile to get `github-push-action` to work, but was going in circles. At least `add-and-commit` was letting me actually push to the branch.

**Comment by EndBug** [comment]
I think the problem comes from the fact that you're telling `add-and-commit` that you're using the `documentation` branch, while you're actually using the `test-doc-action-master` branch. 
What you're trying to do is not just "adding and committing", you're trying to add a folder crated in one branch to another one.
I may be wrong, but if you were to do this with git commands, you'd need to use `git subtree`, which is out of the scope of this action.

I think it would be easier for you to just use plain git commands.

**Comment by cadop** [comment]
ah so the `branch` argument is not the branch you want to commit to, its the branch you are currently on?

**Comment by EndBug** [comment]
Yup, exactly
