### ISSUE TITLE
TypeError: (e || "").replace is not a function ...

### ISSUE THREAD

**Issue by felixlapalma** [EndBug/add-and-commit#25]
Hi, 

Basically I run some scripts on my [repository](https://github.com/felixlapalma/covid19-argentina-viz) and then add and commit files. I was using your action til this morning when it started to [fail](https://github.com/felixlapalma/covid19-argentina-viz/actions/runs/82068134). I attached the step [7_Commit changes.txt](https://github.com/EndBug/add-and-commit/files/4498998/7_Commit.changes.txt)
- Running github actions on Ubuntu latest (add-and-commit/v4)

Thanks!

**Comment by EndBug** [comment]
Hi, thanks for opening the issue!
I think I've figured out what causes that message: it should be a problem in the error handling. With that said, it means that there has been an error in the execution of the script, so I need a little help from you for the debugging.

Please try to run the workflow using the action from the master branch ("fixed"), so that we can see what's the underlying error and see what we can do ;)
You can do that by using `EndBug/add-and-commit@master` in your workflow.

After you do it, please let me know how it ended

**Comment by felixlapalma** [comment]
Hi! thanks for your quick response!
I tried your suggestion on branch [test](https://github.com/felixlapalma/covid19-argentina-viz/tree/test_workflow) and the workflow went smoothly.  Both runs are (slightly different conditions):
 - [Test Workflow](https://github.com/felixlapalma/covid19-argentina-viz/actions/runs/82280493)
- [Test Workflow py](https://github.com/felixlapalma/covid19-argentina-viz/actions/runs/82283000)

All went well! Thanks again!

**Comment by EndBug** [comment]
Happy to hear that! Even though it fixed by itself I've now published the fixes in version `v4.0.2`: I suggest that you now put back `v4` as ref in the workflow so that you don't end up accidentally using some untested version ;)
Thanks again for the issue and good luck with your project!

**Comment by EndBug** [comment]
@all-contributors please add @felixlapalma for bug
