### ISSUE TITLE
Amend commit

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [EndBug/add-and-commit#306]
Is it possible to amend the commit?

**Comment by EndBug** [comment]
To be honest, I've never had to amend commits in pull requests, so I don't really know how GitHub handles PR commits. Also, dependabot might mess up the commit history of its branches, since it always force-pushes when it updates a PR: it's the intended behavior for Dependabot's typical use case, but I don't know how it affects the commit history of the branch...

**Comment by EndBug** [comment]
This feature has been added in `v8.0.0` (also `v8` and `latest`). Thanks for your issue!
