### ISSUE TITLE
Remove mandatory pulling, use whatever has been checked out.

### ISSUE THREAD

**Issue by Darylgolden** [EndBug/add-and-commit#327]
Hi, I'm trying to use this action to make changes to a PR branch, at https://github.com/ManimCommunity/manim/pull/2333. When I try to commit however, I get `Error: Error: There is no tracking information for the current branch.`. This can be seen in the Add & Commit step [here](https://github.com/ManimCommunity/manim/runs/4339082979?check_suite_focus=true). How should I fix this?

**Comment by EndBug** [comment]
It seems like the action is trying to pull from `ManimCommunity:translation-ci` instead of `Darygolden:translation-ci`
I don't think there's a way to work around this with the current action code, I think you have to fall back to using git commands for now.

I'll work towards changing the behavior of the action, since I don't like the fact that it has to pull from the branch: I want it to just use whatever has been checked out (which in case of a PR is probably a detached HEAD, not even a branch...)

Sorry for the inconvenient :/

**Comment by EndBug** [comment]
@all-contributors please add @Darylgolden for their bug report

**Comment by EndBug** [comment]
This fix has been added in `v8.0.0` (also `v8` and `latest`). Thanks for your issue!
