### ISSUE TITLE
Job level `working-directory` does not honor 

### ISSUE THREAD

**Issue by pratikbalar** [EndBug/add-and-commit#339]
**Describe the bug**

Specifying  `working-directory` at job level does not follow by this action

![image](https://user-images.githubusercontent.com/68642400/146309289-b3ffa9a1-39a4-42d4-affe-ad58291f08ef.png)

So I have to do this

![image](https://user-images.githubusercontent.com/68642400/146309394-a85b7585-d513-444a-82ce-2987416ddde2.png)

Instead of this

![image](https://user-images.githubusercontent.com/68642400/146309376-9dc45a5b-72f1-47d4-824a-b0a23e7702cd.png)

**Expected behavior**

It should honor `working-directory` specified at job level

**Logs**
<details>
  <summary>Logs</summary>
<pre><code>
Run EndBug/add-and-commit@v7
  with:
    author_name: GoModTidyer
    author_email: <GoModTidyer@users.noreply.github.com>
    message: fix: go mod tidy
    add: go.*
    branch_mode: throw
    cwd: .
    default_author: github_actor
    pathspec_error_handling: ignore
    push: true
    github_token: ***

Running in /runner/_work/xxxxx/xxxxx
Add input parsed as single string, running 1 git add command.
> Using 'GoModTidyer <<GoModTidyer@users.noreply.github.com>>' as author.
> Using "fix: go mod tidy" as commit message.
Internal logs
  > Staging files...
  > Adding files...
  Error: Error: fatal: pathspec 'go.*' did not match any files
  
  > No files to remove.
  > Checking for uncommitted changes in the git working tree...
> Working tree clean. Nothing to commit.
Outputs
  committed: false
  commit_sha: undefined
  pushed: false
  tagged: false
</code></pre>
</details>

**Comment by EndBug** [comment]
Sure, that seems like a good feature!

**Comment by pratikbalar** [comment]
Well that's how actions should work so i don't think that's feature, it's more like bug.

**Comment by EndBug** [comment]
No, it's really not.
The default you're using is intended for `run` jobs, and not `uses` job (as you can clearly see in the [docs for `jobs.<job_id>.defaults`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#defaultsrun)). At the moment, there's no standard working directory default for other GitHub Actions.
That means that my action would need to see what default working directory you're using for shells, and then replace its `cwd` input with that.

Now that you make me think about it, it would likely be breaking existing workflows, and since the action already has a `cwd` input that can be used in these cases, I likely won't add this feature.

**Comment by pratikbalar** [comment]
No worries, just wanted to point that thing. Thanks for clarification.
