### ISSUE TITLE
Action without permissions

### ISSUE THREAD

**Issue by afonsojramos** [EndBug/add-and-commit#347]
I was testing an action that was triggered on tag creation that updated the package version.

However, I am getting a `Permission to afonsojramos/parrot.git denied to github-actions[bot].`, do you have any idea why?

You can checkout the workflow [here](https://github.com/afonsojramos/parrot/runs/4769349707?check_suite_focus=true).

![image](https://user-images.githubusercontent.com/19473034/148864305-86893d7a-e5e2-41ad-85bc-43ccb6b85238.png)

**Comment by EndBug** [comment]
Hi, I'm afraid that the problem is caused by the fact that you're running in a forked repo: forked repo tokens have restricted permissions for security reasons. If you need more info about it, there have been some discussions in the GitHub forums: [1](https://github.community/t/github-action-workflow-is-executed-for-a-pr-from-a-forked-repo-if-the-pr-changes-the-workflow-file/16059), [2](https://github.community/t/token-permissions-for-forks-once-again/16468)

You can try using a Personal Access Token instead of the built-in token, but beware of the fact that using a PAT will trigger CI on the resulting commit, so make sure you're not creating a loop!

**Comment by afonsojramos** [comment]
That fixed it, thanks @EndBug!

**Comment by afonsojramos** [comment]
@EndBug Quick question, if the branch is protected what is the best approach? To allow for force push? Or to also use the PAT from the repo owner?

**Comment by EndBug** [comment]
I think it depends on the situation: the action behaves like the PAT's user, so if they have permission to force push the action will have it too. It's up to you to decide whether you need the protection rule or if you want to add an exception.
Unfortunately, I don't think there's a way to create an exception for CI without granting more access to the PAT's user.

Happy to know that you managed to fix it 😄

**Comment by afonsojramos** [comment]
I was actually asking in the case that it wasn't a forked repo aka somewhere where the PAT was not obligatory, **however** had a protected branch.

**Comment by EndBug** [comment]
Oh, ok, then I think you would need to use a PAT if you're planning on using administrator privileges. Otherwise, if the branch protection rules do not prevent pushing (like if, for example, they just prevent you from deleting the branch) then the default token should work fine.
In general, I try not to use PATs if they're not necesssary

**Comment by afonsojramos** [comment]
My thoughts exactly, thanks!
