### ISSUE TITLE
Workflow failing

### ISSUE THREAD

**Issue by j-tesla** [EndBug/add-and-commit#405]
**Describe the bug**
Workflow is failing and the code is not getting pushed. 

**Workflow used**
[workflow](https://github.com/j-tesla/blog-list/blob/c124dbc44579463a4ed7d12289f53946df9469bb/.github/workflows/node.js.yml)
**Expected behavior**
I expected that it would not fail.
**Logs**
Either provide a link to the action run or (if your repo is private) paste here the logs from the step that uses it. If you paste the logs, please use this template, and remember to paste the logs from all the different sections.

[workflow run](https://github.com/j-tesla/blog-list/runs/6788298276?check_suite_focus=true#step:9:81)
<details>
  <summary>Logs</summary>
<pre><code>
Error: Error: fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use
    git push origin HEAD:<name-of-remote-branch
</code></pre>
</details>

**Comment by EndBug** [comment]
It seems like you're trying to use the action with PRs, please read the ["Working with PRs" FAQ](https://github.com/EndBug/add-and-commit#working-with-prs) in the README

**Comment by JasurbekA** [comment]
I am not using this with PR, but still failing with similar message

**Comment by EndBug** [comment]
@JasurbekA Open a separate issue and fill the "bug report" issue template

**Comment by JasurbekA** [comment]
@EndBug I have the very same message with a different project name. Feels like I do not have to create a new issue. Thus, I upvoted this issue. Any update or planned date to fix the issue?

**Comment by EndBug** [comment]
@JasurbekA If you're not using this with PRs then you have to open a new issue, because your workflow will be different: as you can see the issue template not only requires you to paste the logs (or, preferably, a link to the failed action run), but the workflow file too.
If you are using this with PRs then the reply is the same as the one I gave the author

Keeping posting in this issue is only notifying the author without the need to, and preventing the issue from becoming stale.
