### ISSUE TITLE
What need I to do next to let the action run well

### ISSUE THREAD

**Issue by CornWorld** [EndBug/add-and-commit#426]
There is an action that was created two months ago, but during this time Github updated the policy so that it became invalid.
Could anyone help me to fix it or give some suggestions?

Below is the error log(part):
```
Outputs
  committed: true
  commit_long_sha: 9ce9daec27b74630db7be68e53ed7b848b72d6f6
  commit_sha: 9ce9dae
  pushed: false
  tagged: false
  tag_pushed: false
Error: Error: Pushing to https://github.com/HadTeam/cdMir
POST git-receive-pack (2245 bytes)
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: At least 1 approving review is required by reviewers with write access.
```
Full failed log is here: https://github.com/HadTeam/cdMir/runs/8043281983
And the config file is here: https://github.com/HadTeam/cdMir/blob/main/.github/workflows/updateWebsite.yml

**Comment by EndBug** [comment]
It's not working because you're trying to push to a protected branch that requires at least 1 review, so you should open a PR, instead of pushing directly.
You need to either change the branch protection rule or [use a PAT](https://github.com/EndBug/add-and-commit#about-tokens) to push the action as if it were you.

**Comment by CornWorld** [comment]
thanks
