### ISSUE TITLE
A fork repo PR permission

### ISSUE THREAD

**Issue by GrapeBaBa** [EndBug/add-and-commit#478]
A similar issue like #369 , can a PR from a fork user got permission?  https://github.com/GrapeBaBa/sui4j/actions/runs/4114786329/jobs/7114924387

**Comment by EndBug** [comment]
If you're using the `pull_request` event, the workflow will run in the fork context, without access to your own repo.
If you want to push to your repo you'll have to run the workflow using the `pull_request_target` event, so that it runs the code in your own repo, and then checkout the other repo's branch.
Keep in mind that you might not have the permissions to push to that fork.

Further reading:
- [This action's README > FAQ > Working with PRs](https://github.com/EndBug/add-and-commit#working-with-prs)
- [`pull_request_target` trigger docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)
- [GitHub's Blog > GitHub Actions improvements for fork and pull request workflows](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/)
