### ISSUE TITLE
unable to access <repo>: The requested URL returned error: 403

### ISSUE THREAD

**Issue by steled** [EndBug/add-and-commit#491]
**Describe the bug**

Hi, I'm trying to use the action for `terraform fmt` to format my modules. The terraform step is running but after that the add and commit fails.
Maybe someone has an idea.

btw. the checkbox from https://github.com/EndBug/add-and-commit/issues/483 is checked.

I'm getting the following error:

```console
Error: Error: Pushing to https://github.com/steled/terraformmodules
remote: Permission to steled/terraformmodules.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/steled/terraformmodules/': The requested URL returned error: 403
```

The same happens if I remove the [lines](https://github.com/steled/terraformmodules/blob/github-actions/.github/workflows/terraform.yml#L41-L42)

**Workflow used**
I'm using this [workflow](https://github.com/steled/terraformmodules/blob/541065b804d8adcf8035507c23945087fb85873c/.github/workflows/terraform.yml)

**Expected behavior**
The changes will be pushed back to the PR.

**Logs**
See the [logs](https://github.com/steled/terraformmodules/actions/runs/4535583400/jobs/7991213909)

**Comment by EndBug** [comment]
Hi, I think the issue is that you're manually setting the permissions only for pull requests ([lines](https://github.com/steled/terraformmodules/blob/541065b804d8adcf8035507c23945087fb85873c/.github/workflows/terraform.yml#L16-L17))
That means that even if you changed the default permissions to the less restrictive setting, it still blocks access to contents because you haven't granted it.
Try removing those two lines and see if it works ;)

**Comment by steled** [comment]
Thank you very much, that was it actually.
