### ISSUE TITLE
"add" with array input doesn't seem to work

### ISSUE THREAD

**Issue by yaakov-h** [EndBug/add-and-commit#533]
**Describe the bug**
When using "add" with multiple inputs as a JSON or YAML array, it logs an error and does not add any files.

**Workflow used**
YAML array (multiline list): https://github.com/pyconau/2023-website/commit/0f778f1f7d00d333026795316d9c2967eed0991d
JSON array (single line): https://github.com/pyconau/2023-website/commit/d3f72484808941d5caa7dd16530215326e81881a

**Expected behavior**
Multiple invocations of `git add` would be run to add multiple directories to the git staging area

**Logs**
https://github.com/pyconau/2023-website/actions/runs/5878006660/job/15939224675

>  Error: Error: fatal: pathspec '-' did not match any files

https://github.com/pyconau/2023-website/actions/runs/5878046329/job/15939335610

>  Error: Error: fatal: pathspec '["public/people",' did not match any files

**Comment by EndBug** [comment]
Hi, I see that you're using an old version of the action: can you update to the latest one and try again?
You can find all breaking changes in the release notes ;)

**Comment by tommie** [comment]
If anyone else ends up here because they are confused...

The `add` data is a multiline string interpreted as a YAML array, like OP tried. The problem is OP used a very old version (v5.3.0) while arrays has been supported [since v6](https://github.com/EndBug/add-and-commit/commit/6f812a4e2c9b0def0dba500d19550e807a46ba1f).
