### ISSUE TITLE
v5 is not released

### ISSUE THREAD

**Issue by robsontenorio** [EndBug/add-and-commit#61]
Example from README 

`    - uses: EndBug/add-and-commit@v5 `

But on github actions 

![image](https://user-images.githubusercontent.com/118955/94351783-c9913180-0033-11eb-9e69-b078fe6d41e0.png)

**Comment by EndBug** [comment]
Yeah, that's from the docs that are supposed to end up in `v5`. I merged the branch into master 2 days ago because I though I would be able to publish it the same day, but I got caught up with some stuff and I didn't do it. I'll publish it very soon though.

You can still refer to `v4` if you need to use the action:
- Repo @ v4: https://github.com/EndBug/add-and-commit/tree/v4
- Marketplace: https://github.com/marketplace/actions/add-commit

**Comment by EndBug** [comment]
Anyway, I've published it now, you should be able to use `v5`

**Comment by robsontenorio** [comment]
Thank you!
