### ISSUE TITLE
Include action name in default message

### ISSUE THREAD

**Issue by Cyberbeni** [EndBug/add-and-commit#64]
I think this would be useful for people.

**Comment by EndBug** [comment]
You're probably right, thanks for the issue!

**Comment by EndBug** [comment]
What about `Commit from GitHub Actions (EndBug/add-and-commit)`, is it ok?

**Comment by Cyberbeni** [comment]
I mean using the name of the workflow/job(maybe even step) that it was used from, so for example it would default to `Commit from GitHub Actions (Build/Build compiled JS version)` when used here: https://github.com/EndBug/add-and-commit/blob/8693022acf06992eb2e7826f13a830b11caaf1e8/.github/workflows/build.yml#L24

Based on [this](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables), GITHUB_WORKFLOW env var is available. (I don't know if the job/step name is available)

**Comment by EndBug** [comment]
Oh, I get it. I'll take a look and see what I can do then 👍

**Comment by EndBug** [comment]
It seems like the `GITHUB_WORKFLOW` is accessible as a variable, but the actual job that's running can only be accessed via the [`github` context](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context): that means if you write `${{ github.job }}` inside the commit message parameter it will be parsed, but I don't think I can access it, since it's not an env variable.

What about `Commit from GitHub Actions ($GITHUB_WORKFLOW)` then?

**Comment by Cyberbeni** [comment]
Sounds good, most of the use cases will be clearly recognizable just by the workflow name (And you can still specify your own message if you need to commit multiple times inside a workflow and want to make them easily distinguishable)

**Comment by EndBug** [comment]
Ok, the change is published in `v5.1.0` (mirrored by `v5` and `latest`)
Thanks again for the issue ;)
