### ISSUE TITLE
Not sure how to use add-and-commit to push changes from master to gh-pages

### ISSUE THREAD

**Issue by philipmjohnson** [EndBug/add-and-commit#78]
Hi, 

I am trying to:

  1.  Run jsdoc on my src files located in the master branch to generate HTML documentation in a top-level api-docs/ directory.
  2. Commit these changes to the gh-pages branch (so that I can see them in a browser).

My workflow is here:

https://github.com/radgrad/radgrad2/blob/master/.github/workflows/jsdoc.yml

But when it runs, it doesn't see any changes so nothing is committed:

https://github.com/radgrad/radgrad2/runs/1333440463?check_suite_focus=true

I know I am missing something simple here, probably with git, but perhaps with your package. Could you advise me on what to do differently?

Thanks!

**Comment by EndBug** [comment]
I think the easiest thing for you to do is, ironically, not to use the action at all: there's an NPM package called [`gh-pages`](https://www.npmjs.com/package/gh-pages#command-line-utility) that can do exactly that. 
You can set up a couple of npm scripts and a GH workflow to handle that, here's an example from one of my repos, where I'm deploying the build of a React app to the `gh-pages` branch:
- [Workflow](https://github.com/EndBug/nikzionario/blob/master/.github/workflows/deploy.yml)
- [package.json](https://github.com/EndBug/nikzionario/blob/master/package.json#L37)

The point is that if you wanted to do this with git commands, you would need to use `git subtree push` instead of `git push`, and my action does not support that. ([this gist](https://gist.github.com/cobyism/4730490) explains it better)
I want this action to be general-purpose, and not to become too complex. I also believe that there are some actions that can deploy to gh-pages, but I can't tell you which one is better since I'm not using  any of them.

**Comment by philipmjohnson** [comment]
Thank you so much!  This is exactly what I needed to know.
